"""
ChartSpec model - the canonical schema for chart configuration.

This is the single source of truth for all chart configurations:
- Generated by AI suggestions (populates Chart Editor)
- Edited by users in the Chart Editor UI
- Validated and rendered by the chart render service
- Stored for saved charts
"""
from typing import Optional, List, Literal, Dict, Any, Union
from pydantic import BaseModel, Field


# =============================================================================
# Enums (using Literal for Pydantic v2 compatibility)
# =============================================================================

ChartTypeEnum = Literal["bar", "line", "scatter", "histogram", "box", "pie", "area", "heatmap"]
AggregationMethodEnum = Literal["none", "sum", "mean", "count", "median", "min", "max"]
LegendPositionEnum = Literal["top", "bottom", "left", "right", "none"]
StackingModeEnum = Literal["grouped", "stacked", "percent"]
ModebarDisplayEnum = Literal["always", "hover", "hidden"]
TooltipDetailEnum = Literal["summary", "detailed"]
ThemeEnum = Literal["light", "dark"]
ColorPaletteEnum = Literal["default", "vibrant", "pastel", "monochrome", "colorblind_safe"]
ExportFormatEnum = Literal["png", "svg", "jpeg", "webp"]
FilterOperatorEnum = Literal["eq", "ne", "gt", "gte", "lt", "lte", "in", "not_in", "between", "contains"]


# =============================================================================
# Color Palette Definitions
# =============================================================================

COLOR_PALETTES: Dict[str, List[str]] = {
    "default": ["#636EFA", "#EF553B", "#00CC96", "#AB63FA", "#FFA15A", "#19D3F3", "#FF6692", "#B6E880"],
    "vibrant": ["#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00", "#FFFF33", "#A65628", "#F781BF"],
    "pastel": ["#B3E2CD", "#FDCDAC", "#CBD5E8", "#F4CAE4", "#E6F5C9", "#FFF2AE", "#F1E2CC", "#CCCCCC"],
    "monochrome": ["#252525", "#525252", "#737373", "#969696", "#BDBDBD", "#D9D9D9", "#F0F0F0"],
    "colorblind_safe": ["#0072B2", "#E69F00", "#009E73", "#CC79A7", "#56B4E9", "#D55E00", "#F0E442"],
}


# =============================================================================
# 1. Data & Mapping Configs
# =============================================================================

class AxisConfig(BaseModel):
    """Configuration for X-axis."""
    column: str
    label: Optional[str] = None


class YAxisConfig(BaseModel):
    """Configuration for Y-axis, supporting multiple columns."""
    columns: List[str]
    label: Optional[str] = None


class FilterCondition(BaseModel):
    """Single filter condition on a column."""
    column: str
    operator: FilterOperatorEnum
    value: Union[str, int, float, List[Any], None]
    value_end: Optional[Union[str, int, float]] = None  # For "between" operator


class FiltersConfig(BaseModel):
    """Filter configuration for data subsetting."""
    conditions: List[FilterCondition] = Field(default_factory=list)
    logic: Literal["and", "or"] = "and"


class SeriesConfig(BaseModel):
    """Configuration for data series/grouping."""
    group_column: Optional[str] = None  # Category dimension to split series
    size_column: Optional[str] = None   # For scatter plots (bubble size)


class AggregationConfig(BaseModel):
    """How to aggregate data before charting."""
    method: AggregationMethodEnum = "none"
    group_by: Optional[List[str]] = None


# =============================================================================
# 2. Visual Structure & Readability Configs
# =============================================================================

class LegendConfig(BaseModel):
    """Legend display configuration."""
    visible: bool = True
    position: LegendPositionEnum = "right"


class VisualStructureConfig(BaseModel):
    """Visual structure and readability settings."""
    title: Optional[str] = None
    stacking: StackingModeEnum = "grouped"
    secondary_y_axis: bool = False


# =============================================================================
# 3. Interaction & Behavior Configs
# =============================================================================

class InteractionConfig(BaseModel):
    """Interactive behavior settings (maps to Plotly config)."""
    zoom_scroll: bool = True
    responsive: bool = True
    modebar: ModebarDisplayEnum = "hover"
    export_formats: List[ExportFormatEnum] = Field(default_factory=lambda: ["png"])
    tooltip_detail: TooltipDetailEnum = "summary"


# =============================================================================
# 4. Styling Presets
# =============================================================================

class StylingConfig(BaseModel):
    """Styling presets (simple options instead of full Plotly style API)."""
    color_palette: ColorPaletteEnum = "default"
    theme: ThemeEnum = "light"
    show_data_labels: bool = False


# =============================================================================
# Main ChartSpec
# =============================================================================

class ChartSpec(BaseModel):
    """
    Canonical chart specification - the single source of truth for chart configuration.
    
    Organized into 4 categories:
    1. Data & Mapping - What the chart means
    2. Visual Structure - How information is presented
    3. Interaction - User interaction behaviors
    4. Styling - Visual appearance presets
    """
    
    # === Data Source ===
    file_id: str
    sheet_name: Optional[str] = None
    
    # === 1. Data & Mapping ===
    chart_type: ChartTypeEnum
    x_axis: AxisConfig
    y_axis: Optional[YAxisConfig] = None
    series: Optional[SeriesConfig] = None
    aggregation: AggregationConfig = Field(default_factory=AggregationConfig)
    filters: Optional[FiltersConfig] = None
    
    # === 2. Visual Structure & Readability ===
    visual: VisualStructureConfig = Field(default_factory=VisualStructureConfig)
    legend: LegendConfig = Field(default_factory=LegendConfig)
    
    # === 3. Interaction & Behavior ===
    interaction: InteractionConfig = Field(default_factory=InteractionConfig)
    
    # === 4. Styling Presets ===
    styling: StylingConfig = Field(default_factory=StylingConfig)
    
    # === Metadata ===
    version: str = "1.0"


# =============================================================================
# Request/Response Models for API
# =============================================================================

class ChartRenderRequest(BaseModel):
    """Request for POST /api/charts/render."""
    spec: ChartSpec


class ChartRenderResponse(BaseModel):
    """Response for POST /api/charts/render."""
    chart_json: Dict[str, Any]
    rendered_at: str
    spec_version: str = "1.0"


class ChartValidateRequest(BaseModel):
    """Request for POST /api/charts/validate."""
    spec: ChartSpec


class ChartValidateResponse(BaseModel):
    """Response for POST /api/charts/validate."""
    valid: bool
    errors: List[Dict[str, Any]] = Field(default_factory=list)
    warnings: List[Dict[str, Any]] = Field(default_factory=list)


class AISuggestRequest(BaseModel):
    """Request for POST /api/charts/suggest."""
    file_id: str
    sheet_name: Optional[str] = None
    user_instructions: Optional[str] = None
    current_spec: Optional[ChartSpec] = None


class AISuggestResponse(BaseModel):
    """Response for POST /api/charts/suggest."""
    suggested_spec: ChartSpec
    explanation: str
    confidence: float
    alternatives: List[Dict[str, str]] = Field(default_factory=list)
    usage: Dict[str, Any] = Field(default_factory=dict)
